### PR TITLE
Fix language list displaying non-languages in list.

### PR DESCRIPTION
**Pull request by Arek75**
hcjiv1 fixed this by unsetting the default news language, which caused news fetching to fail if a language wasn't explicitly set.  My fix is a bit more complex, but leaves news set to "en" by default.

### CODE REVIEW

**Comment by nwestfal** [comment]
This one has merge conflicts, I guess with the other pulls I just merged.

**Comment by Arek75** [comment]
I'll look into it, thanks.

**Comment by Arek75** [comment]
Should work now.

**Comment by Arek75** [comment]
grr, gotta fix a merge error. :/

**Comment by Arek75** [comment]
Finally got the thing properly merged for you, and removed a line of debugging code I'd forgotten to remove before pushing whil I was at it.

**Pull request merged**
