### PR TITLE
Fix for unicode errors on Python 3.x for Windows

### PR DESCRIPTION
**Pull request by Arek75**
I didn't test whether this would affect wine or not, but I don't want to take the chance.  In any case, Python 3's built-in open() writes files in the native codepage by default.  This works fine until you run into a character not supported in your native codepage, such as \ufeff (from the DDO world config) on cp1252 (the default for many Windows machines in the US), at which point Python (rightly) throws an exception.

This fixes that issue by creating a 'uopen' wrapper that points to open() on Python 2.x and codecs.open() on Python 3.x.  I tried just using codecs.open directly, but then Python 2.x throws an exception about converting ascii strings to unicode for it.

### CODE REVIEW

**Comment by Arek75** [comment]
this isn't ready.  I'll comment again when it is, sorry for the noise.

**Comment by Arek75** [comment]
ok, fixed.  This seems to work, at least for me, on both Python 2 and Python 3.

**Comment by Arek75** [comment]
And ready.  In this case, the whitespace problems didn't cause errors, but they are unsightly if you have a different tab-size than someone else in a file that mostly uses tabs and not spaces for indentation.

**Comment by nwestfal** [comment]
I'll test this out.  Thanks for all the work you are doing on this.  I hadn't noticed any issues with it, other than sometimes pylotro locks up after exiting LotRO.

**Comment by Arek75** [comment]
If you're using Python 2 or you're using a unicode locale, this won't affect you at all.  It only affects users using Python 3 on a non-unicode locale.  More testing won't hurt, tho, as the changes aren't trivial. :)

**Pull request merged**
